"""empty message

Revision ID: 71d3ba54f0dd
Revises: 97552737fa5a
Create Date: 2019-08-01 10:07:32.527668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d3ba54f0dd'
down_revision = '97552737fa5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('look_create_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('look_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'look_time')
    op.drop_column('user', 'look_create_at')
    # ### end Alembic commands ###
